<h3>IMPORT CLEAN DATA</h3>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# path of data 
path = 'clean_df_automobile.csv'
df = pd.read_csv(path)
df.head()

,symboling,normalized-losses,make,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,compression-ratio,horsepower,peak-rpm,city-L/100km,highway-L/100km,price,fuel-type-diesel,fuel-type-gas,aspiration-std,aspiration-turbo
0,3,122,alfa-romero,two,convertible,rwd,front,88.6,0.811148,0.890278,...,9.0,111.0,5000.0,11.190476,8.703704,13495.0,0,1,1,0
1,3,122,alfa-romero,two,convertible,rwd,front,88.6,0.811148,0.890278,...,9.0,111.0,5000.0,11.190476,8.703704,16500.0,0,1,1,0
2,1,122,alfa-romero,two,hatchback,rwd,front,94.5,0.822681,0.909722,...,9.0,154.0,5000.0,12.368421,9.038462,16500.0,0,1,1,0
3,2,164,audi,four,sedan,fwd,front,99.8,0.848630,0.919444,...,10.0,102.0,5500.0,9.791667,7.833333,13950.0,0,1,1,0
4,2,164,audi,four,sedan,4wd,front,99.4,0.848630,0.922222,...,8.0,115.0,5500.0,13.055556,10.681818,17450.0,0,1,1,0

<h3>LINEAR REGRESSION</h3>


Y hat = a + bX

In [28]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()                               # buat objek linear regression
lm.fit(df[['highway-L/100km']], df[['price']])        # membuat fungsi linear dengan highway-L/100km sebagai prediktor dan "price" sebagai response variable
Yhat=lm.predict(df[['highway-L/100km']])              # Y hat = a + bX

print("contoh 1")
print("==================================================")
print("Prediktor(X) : highway-L/100km | Response(Y) : price")
print("==================================================")
print("5 prediksi harga teratas : \n", Yhat[0:5])
print("\nIntercept     (a) : ", lm.intercept_)
print("Gradien/Slope (b) : ", lm.coef_)
print("model linear -> price =", lm.intercept_[0] ,"+", lm.coef_[0][0] ,"x highway-L/100km")
print("==================================================")


# engine-size dan price
lm1 = LinearRegression()
lm1.fit(df[['engine-size']], df[['price']])
print("\n\ncontoh 2")
print("==================================================")
print("Prediktor (X) : engine-size | Response (Y) : price")
print("==================================================")
print("Intercept     : ", lm1.intercept_)
print("Gradien/Slope : ", lm1.coef_)
print("model linear -> price =", lm1.intercept_[0] ,"+", lm1.coef_[0][0] ,"x engine-size")
print("==================================================")

contoh 1
==================================================
Prediktor(X) : highway-L/100km | Response(Y) : price
==================================================
5 prediksi harga teratas :
 [[15485.52737455]
 [15485.52737455]
 [16643.34931414]
 [12475.19033163]
 [22327.2024721 ]]

Intercept     (a) :  [-14617.84305466]
Gradien/Slope (b) :  [[3458.68511314]]
model linear -> price = -14617.843054664598 + 3458.685113143813 x highway-L/100km
==================================================


contoh 2
==================================================
Prediktor (X) : engine-size | Response (Y) : price
==================================================
Intercept     :  [-7963.33890628]
Gradien/Slope :  [[166.86001569]]
model linear -> price = -7963.338906281024 + 166.8600156914158 x engine-size
==================================================

<h3>MULTIPLE LINEAR REGRESSION</h3>


Y hat = a + b1X1 + b2X2 + ... + bnXn

In [34]:
lm2 = LinearRegression()
lm2.fit(df[['horsepower', 'curb-weight', 'engine-size', 'highway-L/100km']], df['price'])
print("==================================================")
print("            MULTIPLE LINEAR REGRESSION")
print("==================================================")
print("Intercept     : ", lm2.intercept_)
print("Gradien/Slope : ", lm2.coef_)
print("model linear -> price =", lm2.intercept_ ,"+", lm2.coef_[0] ,"x horsepower +", lm2.intercept_ ,"+", lm2.coef_[1], "x curb-weight", lm2.intercept_ ,"+", lm2.coef_[2], "x highway-L/100km")
print("==================================================")

==================================================
            MULTIPLE LINEAR REGRESSION
==================================================
Intercept     :  -14386.530839268187
Gradien/Slope :  [ 36.60566451   3.50008296  85.38595269 500.93378897]
model linear -> price = -14386.530839268187 + 36.60566451102235 x horsepower + -14386.530839268187 + 3.500082961963926 x curb-weight -14386.530839268187 + 85.38595269279804 x highway-L/100km
==================================================

In [35]:
# length dan price
lm3 = LinearRegression()
lm3.fit(df[['length']], df[['price']])
print("Intercept     : ", lm3.intercept_)
print("Gradien/Slope : ", lm3.coef_)

Intercept     :  [-64384.43632742]
Gradien/Slope :  [[92690.65779928]]

In [36]:
# korelasi wheel-base, height, price
df[['wheel-base','height','price']].corr()

            wheel-base    height     price
wheel-base    1.000000  0.590742  0.584642
height        0.590742  1.000000  0.135486
price         0.584642  0.135486  1.000000

In [37]:
# korelasi peak-rpm, horsepower, highway-L/100km, price
df[['peak-rpm','horsepower','highway-L/100km','price']].corr()

                 peak-rpm  horsepower  highway-L/100km     price
peak-rpm         1.000000    0.107885         0.017694 -0.101616
horsepower       0.107885    1.000000         0.840608  0.809575
highway-L/100km  0.017694    0.840608         1.000000  0.801118
price           -0.101616    0.809575         0.801118  1.000000